
@startuml

package edp.epam.com {

  package domain {


    class Codebase {
      -- annotations --
      -- metadata --
      -- spec --
      String name
      CodebaseType type
      VCS
      techFramework
      -- status --
    }

    enum CodebaseType {
      APPLICATION
      AUTOTESTS
      LIBRARY
    }
    Codebase -left-> CodebaseType
    Codebase -right[hidden]-> CdPipeline

    class TechologyFramework {
      -- annotations --
      -- metadata --
      -- spec --
        String language
        String jenkinsSlaveAlias
        String jenkinsSlaveVersion
      -- status --
    }
    TechologyFramework -up[hidden]-> CodebaseType
    Codebase --> TechologyFramework

    class CodebaseBranch {
      -- annotations --
      -- metadata --
      -- spec --
        + String name
      -- status --
    }
    Codebase "1" *-down- "many" CodebaseBranch
    CodebaseBranch "1" *-- "many" CodebaseArtifact

    class CodebaseArtifact {
      -- annotations --
      -- metadata --
      -- spec --
        + String commit
        + ArtifactType type
      -- status --
        String version
        String url
    }

    enum ArtifactType {
      ZIP
      JAR
      DOCKER
    }
    CodebaseArtifact -left-> ArtifactType

    class CdPipeline {
      -- annotations --
      -- metadata --
      -- spec --
        CodebaseArtifactStream[] applications
        ThirdPartyService[] services
      -- status --
    }
    CdPipeline "1" --> "*" commands.cdpipeline
    CdPipeline "many" *-d- "many" ThirdPartyService
    CdPipeline "1" *--- "many" CdPipelineStage
    CdPipeline "1" *-- "many" CodebaseArtifactStream
    CodebaseArtifactStream *-r[hidden]- ThirdPartyService

    class CodebaseArtifactStream {
      -- annotations --
      -- metadata --
      -- spec --
        + String name
        + CodbaseArtifact[] availableArtifacts
      -- status --
        String version
        String url
    }
    CodebaseArtifactStream "many" *-d- "many" CodebaseArtifact


    class ThirdPartyService {
      -- annotations --
      -- metadata --
      -- spec --
      -- status --
    }

    class CdPipelineStage {
      -- annotations --
      -- metadata --
      -- spec --
        CdQualityGate[] qualityGates
        TriggerType triggerType
      -- status --
    }
    CdPipelineStage "1" *-- "many" CdQualityGate
    CdPipelineStage "1" *-u- "1" CodebaseArtifactStream : input stream
    CdPipelineStage "1" *-u- "1" CodebaseArtifactStream : output stream
    CdPipelineStage "1" *-- "1" CdPipelineStage : next stage

    enum TriggerType {
      MANUAL
      NEW_ARTIFACT
    }
    CdPipelineStage --> TriggerType



    class CdQualityGate {
      -- annotations --
      -- metadata --
      -- spec --
        CdQualityGateType type
        CodebaseBranch autotest
        String command2Run
        String command2CheckQualityGate
      -- status --

    }
    CdQualityGate "1" *-up- "1" CodebaseBranch

    class CdStageDeploy {
      -- annotations --
      -- metadata --
      -- spec --
        CdPipelineStage stage
        String[] applicationVersion
      -- status --
    }
    CdPipelineStage "1" *-- "many" CdStageDeploy


  }

  package api {
    class DeliverySpace {
      -- annotations --
      -- metadata --
      -- spec --
      EDPComponent[] components
      -- status --
      -- method --
    }


'    enum EdpComponentType {
'      CODE_REVIEW
'      CI_SERVER
'      CD_SERVER
'      STATIC_ANALYSES
'      ARTIFACT_REPOSITORY
'      VCS
'    }
'
'    EdpComponentType "*" -left-> "1" EdpComponent

    enum EdpLocationType {
      EXTERNAL
      INTERNAL
    }
    EdpLocationType "*" --> "1" EdpComponent

    abstract class EdpComponent {
      -- annotations --
      EdpComponentType[] componentTypes
      edpTenant:
      -- metadata --
      -- spec --
      EdpLocationType location
      String version
      String extrenalUrl
      Credentials credentials
      -- status --
      boolean clientActive
      externalUrl
      -- method --
      install()
      configure()
      expose()
      integrate()
    }
    EdpComponent "*" -u-> "1" DeliverySpace

    package vcs {
      class EdpVcsRepository {
      -- annotations --
      -- metadata --
      -- spec --
        String remoteRepoUrl
        Credentials credentials
      -- status --
      }
    }

    package keycloak {
      class Keycloak {
      -- annotations --
      -- metadata --
      -- spec --
      -- status --
      }
      EdpComponent<|--Keycloak

      class KeycloakInstaller {
      -- annotations --
      -- metadata --
      -- spec --
        String version
      -- status --
      }
      KeycloakInstaller <-r- Keycloak : created if type of \n component is internal

      class KeycloakRealm {
      -- annotations --
      -- metadata --
      -- spec --
        String name
      -- status --
      }
      KeycloakRealm -u-> Keycloak : main realm created automatically

      class KeycloakClient {
      -- annotations --
      -- metadata --
      -- spec --
        String name
      -- status --
      }
      KeycloakClient -u-> KeycloakRealm : "created by component\nto enable sso"

      class KeycloakUser {
      -- annotations --
      -- metadata --
      -- spec --
        String username
        String[] roles
      -- status --
      }
      KeycloakUser -u-> KeycloakRealm : "created by keycloak\n operator from keyclok,\n used by other components \n to add into authz model"
    }

    package jenkins {
      class Jenkins {
      -- annotations --
      -- metadata --
      -- spec --
      -- status --
      }
      EdpComponent<|--Jenkins

      class JenkinsInstaller {
      -- annotations --
      -- metadata --
      -- spec --
        String version
      -- status --
      }
      JenkinsInstaller <-r- Jenkins : created if type of component is internal

      class JenkinsPlugin {
      -- annotations --
      -- metadata --
      -- spec --
        String pluginInstruction
      -- status --
      }
      JenkinsPlugin <-d- Jenkins :  processed by Jenkins Operator

      class JenkinsServiceAccount {
      -- annotations --
      -- metadata --
      -- spec --
        Credentials credentials
      -- status --
      }
      JenkinsServiceAccount <-d- Jenkins : processed by Jenkins Operator

      class JenkinsFolder {
      -- annotations --
      -- metadata --
      creates folder with \n create release pipeline
      -- spec --
        String name
      -- status --
      }
      JenkinsFolder <-d- Jenkins : created for each codebase entity \n processed by Jenkins Operator

      class JenkinsJob {
      -- annotations --
      -- metadata --
      -- spec --
        String branch
      -- status --
      }
      JenkinsFolder -d-> JenkinsJob : created for each codebase branch

      class JenkinsJobBuild {
      -- annotations --
      -- metadata --
      -- spec --
      -- status --
      }
      JenkinsJob -d-> JenkinsJobBuild : data about build in Jenkins

      class JenkinsCdPipleine {
      -- annotations --
      -- metadata --
      -- spec --
      -- status --
      }
      JenkinsCdPipleine <-d- Jenkins

      class JenkinsCdPipelineStage {
      -- annotations --
      -- metadata --
      -- spec --
      -- status --
      }
      JenkinsCdPipelineStage <-d- JenkinsCodebase

      class JenkinsCdPipelineStageDeploy {
      -- annotations --
      -- metadata --
      -- spec --
      -- status --
      }
      JenkinsCdPipelineStageDeploy <-d- JenkinsCdPipelineStage
    }

  }


  package components {
    class Gerrit {
      -- annotations --
      componentTypes: CODE_REVIEW, VCS
      -- metadata --
      -- spec --
      -- status --
    }

    class Nexus {
      -- annotations --
      - String is-credentials
      - String ci-credentials
      -- metadata --
      -- spec --
	     + String version
      + Struct volumes
      -- status --
      - Bool Available
      - Time LastTimeUpdated
      - String Status
    }

    class Sonar {
    }
    Sonar -u-> JenkinsPlugin :register plugin for creation
    Sonar -u-> JenkinsServiceAccount :service account for Jenkins
    Sonar -u-> KeycloakClient :register client for SSO

    class BitBucket {
    }


    class Gitlab {
    }
'    EdpComponent<|--Gerrit
'    EdpComponent<|--Nexus
'    EdpComponent<|--Sonar
'    EdpComponent<|--BitBucket
'    EdpComponent<|--Gitlab
  }
}

@enduml