@startuml

package com.epam.edp.nexus {
  class Nexus {
    -- metadata --
    - String is-credentials
    - String ci-credentials
    -- spec --
    + String version
    + Struct volumes
    + Struct users
    -- status --
    - Bool available
    - Time lastTimeUpdated
    - String status
  }

  class NexusInstaller <<tbd>> {
  -- metadata --
  -- spec --
    String version
  -- status --
  }
  NexusInstaller <-r- Nexus : created if type of component is internal


  class NexusUser <<tbd>> {
    -- metadata --
    -- spec --
    + String nexusName (optional)
    + String name
    + Struct role
    + String email
    + String firstName
    + String lastName
    -- status --
    -- reconcile --
    +addUserInNexus()
  }
  NexusUser .u.> Nexus : owner ref

  class NexusScript <<tbd>> {
    -- metadata --
    -- spec --
    + String nexusName (optional)
    + String name
    + String configMapName
    + String configMapKey
    -- status --
    -- reconcile --
    +addScriptInNexus()
  }
  NexusScript .u.> Nexus : owner ref
}


legend
|= arrow   |= meaning|
|  ..>     |   owner references  |
|  -->     |   creates     |
|<back:LightGoldenRodYellow>    </back>| Work In Progress |
|<back:LightGreen>    </back>| Implemented |
|<back:Khaki>    </back>| TBD |
endlegend

skinparam class {
	backgroundColor<<impl>> LightGoldenRodYellow
	backgroundColor<<wip>> LightGreen
	backgroundColor<<tbd>> Khaki
}
@enduml