@startuml

package com.epam.edp.sonar {
  class Sonar {
    -- metadata --
    -- spec --
    + String version
    -- status --
    -- events --
    createSonarCR
    updateSonarCR
    timebound
    -- handlers --
    checkSonarClientConnection()
    getSonarQualityGates()
    getSonarQualityProfiles()
  }

  class SonarInstaller <<tbd>> {
  -- metadata --
  -- spec --
    String version
  -- status --
  }
  SonarInstaller <-r- Sonar : created if type of component is internal

  class SonarQualityProfile<<tbd>> {
    -- metadata --
    -- spec --
    + String profileName
    -- status --
  }
  SonarQualityProfile <-d- Sonar : create

  class SonarQualityGate<<tbd>> {
    -- metadata --
    -- spec --
    + String sonarName (optional)
    + String gateName
    -- status --
  }
  SonarQualityGate <-d-  Sonar : owner ref
}


legend
|= arrow   |= meaning|
|  ..>     |   owner references  |
|  -->     |   creates     |
|<back:LightGoldenRodYellow>    </back>| Work In Progress |
|<back:LightGreen>    </back>| Implemented |
|<back:Khaki>    </back>| TBD |
endlegend

skinparam class {
	backgroundColor<<impl>> LightGoldenRodYellow
	backgroundColor<<wip>> LightGreen
	backgroundColor<<tbd>> Khaki
}
@enduml