@startuml
entity "CR Keycloak" as cr_keycloak
participant "Keycloak-controller" as keycloak_controller
entity "CR Keycloak Realm" as cr_realm
participant "Keycloak-realm-controller" as keycloak_realm_controller

participant "Keycloak Server" as server
entity "CR Keycloak Client" as cr_client

cr_keycloak -> keycloak_controller: Read \n\
**Params:** \n\
Keycloak server web URL \n\
Keycloak admin login \n\
Keycloak admin password \n\
Central Keycloak realm name "Aka Openshift" \n\
Realm name (default value = namespace.main)

activate keycloak_controller
keycloak_controller -> cr_realm: Create \n\
**Params**: \n\
Realm Name \n\
Owner reference
deactivate keycloak_controller

cr_realm -> keycloak_realm_controller: Read\n**Params:**\nRealm Name

activate keycloak_realm_controller
keycloak_realm_controller -> keycloak_realm_controller: Validate params:\nRealm name = namespace.name
keycloak_realm_controller -> cr_keycloak: Read by Owner reference
activate cr_keycloak
cr_keycloak -> keycloak_realm_controller: Keycloak url/login/password
deactivate cr_keycloak
keycloak_realm_controller -> server: Create realm\n**Params:**\nRealm name
keycloak_realm_controller -> server: Update realm with default params
keycloak_realm_controller -> keycloak_realm_controller: Generate EDP Client credentials
keycloak_realm_controller -> cr_client: \
Create client \n\
**Params:** \n\
name: realm name without namespace \n\
is central: true \n\
roles: admin, developer

keycloak_realm_controller -> server: \
Update external identity provider for realm \n\
**Params:** \n\
Central Keycloak realm name \n\
EDP Client credentials

deactivate keycloak_realm_controller

@enduml