@startuml
entity "CR Keycloak" as cr_keycloak
participant "Keycloak-controller" as keycloak_controller
entity "CR Keycloak Realm" as cr_realm
participant "Keycloak-realm-controller" as keycloak_realm_controller

participant "Keycloak Server" as server


cr_keycloak -> keycloak_controller: Read \n\
**Params:** \n\
Keycloak server web URL \n\
Keycloak admin login \n\
Keycloak admin password
activate keycloak_controller
keycloak_controller -> server: Check connection \n\
**Params:** \n\
login \n\
password
keycloak_controller -> cr_keycloak: Update status connected
keycloak_controller -> cr_realm: Create \n\
**Params**: \n\
Realm Name = namespace.main \n\
Owner reference
deactivate keycloak_controller

cr_realm -> keycloak_realm_controller: Read\n**Params:**\nRealm Name

activate keycloak_realm_controller
keycloak_realm_controller -> cr_keycloak: Read by Owner reference
activate cr_keycloak
cr_keycloak -> keycloak_realm_controller: Keycloak url/login/password/connected
deactivate cr_keycloak
keycloak_realm_controller -> keycloak_realm_controller: Check connected status
keycloak_realm_controller -> server: Create realm\n**Params:**\nRealm name
keycloak_realm_controller -> cr_realm: Update status available

deactivate keycloak_realm_controller

@enduml